version: '3'
services:
  consul:
    image: sparkpos/nginx-consul-template
    ports:
      - 80:80
      - 443:443
    environment:
      - CONSUL_PORT_8500_TCP_ADDR=dplor.com
    volumes:
      - ./custom.ctmpl:/etc/nginx/nginx.conf.ctmpl
    container_name: my-consul
