version: '3'
services:
  consul:
    image: sparkpos/nginx-consul-template
    ports:
      - 80:80
      - 443:443
    environment:
      - CONSUL_PORT_8500_TCP_ADDR=dplor.com
      - SERVICE_IGNORE=true
    volumes:
      #- ./nginx.conf.ctmpl:/etc/nginx/nginx.conf.ctmpl
      - /root/certs-wild:/etc/nginx/certs
      - ./dhparam/dhparam.pem:/etc/nginx/dhparam/dhparam.pem
    container_name: consul
